name: mobile
description: Mobile application for hr-app

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.2
  bloc_pattern: ^2.5.1
  retrofit: ^1.3.4
  json_serializable: ^3.3.0
  rxdart: ^0.24.1
  shared_preferences: ^0.5.8
  fluttertoast: ^7.0.2
  logger: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.0
  retrofit_generator: ^1.3.7+2


flutter:
  uses-material-design: true

  assets:
    - assets/i18n/